### ISSUE TITLE
Build error 

### ISSUE THREAD

**Issue by DGoliath** [JDCTeam/android_device_samsung_jfltepie-private#2]
Hi there,
upon building your great Optimized LineageOS 17.1 for the Samsung Galaxy S4 (Qualcomm variants) I ran into an error.

[ 96% 470/485] including vendor/jdc/proprietary/Android.mk ...
FAILED: 
build/make/core/base_rules.mk:325: error: vendor/jdc/proprietary: MODULE.TARGET.APPS.Toolbox already defined by android_vendor_jdc-opt-cm-17.1/proprietary.
22:18:53 ckati failed with: exit status 1
make: *** [build/make/core/main.mk:21: run_soong_ui] Fehler 1

Maybe you guys know of this already, if not may it be of help for you.
Cheers D.

**Comment by dkati** [comment]
@DGoliath sorry about that.we accidentically closed it.

this error means that u have to sync our vendor/jdc too. Optimized Lineage 17.1 is NOT official LineageOS from the Lineage guys. be sure that u want to build OUR custom one or the official one.
